#	$NetBSD$
#
# hwp - Intel Hardware P-states (Speed Shift) enabler with EPP sysctl.
# Build:  cd /usr/src/sys/modules/hwp && make   (S is derived by ../Makefile.inc)

.include "../Makefile.inc"

KMOD=	hwp
SRCS=	hwp.c

.include <bsd.kmodule.mk>
