#!/bin/sh
# powerd lid hook: pressed=closed, released=open. Kernel handles s2idle wake.
PATH=/sbin:/usr/sbin:/bin:/usr/bin:/usr/pkg/sbin:/usr/pkg/bin; export PATH
logger -p info -t lid "lid: $*"
case "$2" in
pressed)  /usr/local/bin/s0ix suspend ;;
released) /usr/local/bin/s0ix resume  ;;
esac
exit 0
