#	$NetBSD$
#
# cidle - MWAIT idle with tunable C-state hint (deep C-states without acpicpu).
# Build:  cd /usr/src/sys/modules/cidle && make

.include "../Makefile.inc"

KMOD=	cidle
SRCS=	cidle.c

.include <bsd.kmodule.mk>
