#	$NetBSD$
#
# patfix - program IA32_PAT on all CPUs (NetBSD 11 only does CPU 0).
# Build:  cd /usr/src/sys/modules/patfix && make

.include "../Makefile.inc"

KMOD=	patfix
SRCS=	patfix.c

.include <bsd.kmodule.mk>
