#!/bin/sh
PATH=/sbin:/usr/sbin:/bin:/usr/bin:/usr/pkg/sbin:/usr/pkg/bin; export PATH
LOG=/root/s2idle.log
echo "==== s2idle test $(date) ====" >> $LOG
sync; sync; sleep 1
echo "PRE  $(date +%s)" >> $LOG
sysctl -w hw.acpi.sleep.freeze=1 >> $LOG 2>&1   # BLOCKS until power-button wake
echo "POST $(date +%s)" >> $LOG
sleep 2; dmesg | grep -i s2idle | tail -6 >> $LOG
echo "---- done ----" >> $LOG; sync
cat $LOG | tail -8
